/* DO NOT EDIT! GENERATED AUTOMATICALLY! */
#if HAVE_WINSOCK2_H
# include <winsock2.h> /* avoid mingw pollution on DATADIR */
#endif
#define PREFIX "/usr/local/m4"
#define EXEC_PREFIX "/usr/local/m4"
#define BINDIR "/usr/local/m4/bin"
#define SBINDIR "/usr/local/m4/sbin"
#define LIBEXECDIR "/usr/local/m4/libexec"
#define DATAROOTDIR "/usr/local/m4/share"
#define DATADIR "/usr/local/m4/share"
#define SYSCONFDIR "/usr/local/m4/etc"
#define SHAREDSTATEDIR "/usr/local/m4/com"
#define LOCALSTATEDIR "/usr/local/m4/var"
#define RUNSTATEDIR "/usr/local/m4/var/run"
#define INCLUDEDIR "/usr/local/m4/include"
#define OLDINCLUDEDIR "/usr/include"
#define DOCDIR "/usr/local/m4/share/doc/m4"
#define INFODIR "/usr/local/m4/share/info"
#define HTMLDIR "/usr/local/m4/share/doc/m4"
#define DVIDIR "/usr/local/m4/share/doc/m4"
#define PDFDIR "/usr/local/m4/share/doc/m4"
#define PSDIR "/usr/local/m4/share/doc/m4"
#define LIBDIR "/usr/local/m4/lib"
#define LISPDIR "/usr/local/m4/share/emacs/site-lisp"
#define LOCALEDIR "/usr/local/m4/share/locale"
#define MANDIR "/usr/local/m4/share/man"
#define PKGDATADIR "/usr/local/m4/share/m4"
#define PKGINCLUDEDIR "/usr/local/m4/include/m4"
#define PKGLIBDIR "/usr/local/m4/lib/m4"
#define PKGLIBEXECDIR "/usr/local/m4/libexec/m4"
